; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
;If VSCode is stuk here, "Uploading .pio\build\nanoatmega328\firmware.hex", most likely the upload speed is too high. Try to lower it.Also install CH340 driver.
upload_speed = 57600
lib_deps = 
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	featherfly/SoftwareSerial@^1.0
	akj7/TM1637 Driver @ ^2.2.1
	smougenot/TM1637@0.0.0-alpha+sha.9486982048
